### ISSUE TITLE
`podman-compose up` error message suggests to use --replace option which is misleading - it does not exist

### ISSUE THREAD

**Issue by Fak3** [containers/podman-compose#1118]
**Describe the bug**

`podman-compose up` gives misleading error message:
```
Error: creating container storage: the container name "podtest_myservice_1" is already in use by 
86c42c65343b40e1ee7798daf3e7493d9fd2c6fcb08467b8730d008c3f88b920. You have to remove 
that container to be able to reuse that name: that name is already in use, 
or use --replace to instruct Podman to do so.
```

But the there is no `--replace` option for docker-compose

**To Reproduce**
1. `mkdir mydir`
1. create minimal docker-compose.yml:
    ```
    services:
      myservice:
        image: alpine
        volumes:
          - ./mydir:/mydir:U
        command: touch /mydir/myfile
    ```
1. run `podman-compose up`
1. run `podman-compose up` again

**Expected behavior**

I expected to get a suggested option to force-replace container with docker-compose. 

**Actual behavior**

Message says to use --replace option which does not exist for docker-compose

**Output**

```
> podman-compose version
podman-compose version 1.3.0
podman version 5.3.1
```

**Environment:**
 - OS: opensuse tumbleweed

**Comment by Fak3** [comment]
Attmpt to pass --replace with --podman-args fails:

```
> podman-compose --podman-args=--replace up
Traceback (most recent call last):
  File "/home/u1/.local/bin/podman-compose", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/u1/.local/share/pipx/venvs/podman-compose/lib64/python3.11/site-packages/podman_compose.py", line 3711, in main
    asyncio.run(async_main())
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/u1/.local/share/pipx/venvs/podman-compose/lib64/python3.11/site-packages/podman_compose.py", line 3707, in async_main
    await podman_compose.run()
  File "/home/u1/.local/share/pipx/venvs/podman-compose/lib64/python3.11/site-packages/podman_compose.py", line 1861, in run
    retcode = await cmd(self, args)
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/u1/.local/share/pipx/venvs/podman-compose/lib64/python3.11/site-packages/podman_compose.py", line 2672, in compose_up
    await compose.podman.output(
  File "/home/u1/.local/share/pipx/venvs/podman-compose/lib64/python3.11/site-packages/podman_compose.py", line 1428, in output
    raise subprocess.CalledProcessError(p.returncode, " ".join(cmd_ls), stderr_data)
subprocess.CalledProcessError: Command 'podman ps --replace --filter label=io.podman.compose.project=podtest -a --format {{ index .Labels "io.podman.compose.config-hash"}}' returned non-zero exit status 125.
```

**Comment by Fak3** [comment]
Another issue - The `podman-compose --podman-args=--replace up` should print the actual error message from podman:
```
Podman returned non-zero exit status 125 
Error: unknown flag: --replace
See 'podman ps --help'
```
Currently it is just uninformative `subprocess.CalledProcessError: Command 'podman ps --replace --filter label=io.podman.compose.project=podtest -a --format {{ index .Labels "io.podman.compose.config-hash"}}' returned non-zero exit status 125.`

**Comment by madsl** [comment]
Is there a way to get around this error? Hitting this myself...

**Comment by madsl** [comment]
Seems like a solution is to use `podman-compose --podman-run-args=--replace up  -d`

**Comment by mattsains** [comment]
I notice that `podman-compose up --force-recreate` exists and is probably what it should recommend?

**Comment by robertaistleitner** [comment]
I guess `podman-compose` should detect if stuff needs to be recreated the same way as docker-compose does it? 

`--force-recreate` has a heavy impact on performance if it blindly recreates all containers if e.g. only settings for a single service changed.

**Comment by rafalkrupinski** [comment]
I'm getting this error when running with the same compose file as before, so it shouldn't even make any complains, just restart services

**Comment by mabasic** [comment]
This is strange. With docker its just starts my services, but with podman-compose it seems like it tries to create the volume again, instead of attaching to the existing volume

**Comment by doc-sheet** [comment]
Hi!

Here is simple fix for this issue #1251

I can try to make it ready for merge if that solution is fine.

**Comment by lh123** [comment]
@doc-sheet 
Just checking in — any update? We're encountering the same issue in the VS Code devcontainer.

**Comment by art-solopov** [comment]
The funny thing is that (for me at least) despite the error, it still starts the container all right.

**Comment by guesant** [comment]
in my opinion, for the best DX and convenience comming from docker-compose, i think that --replace should be default, or a new mode that restarts if changed, otherwise exists 0 with running state

the same for podman compose down if the containers are already stopped

can we have a env for that?

PODMAN_COMPOSE_BEHAVIOUR=optimistic


podman compose up -d # starts the containers
podman compose up -d # always exits 0; if running and nothing has changed, does nothing; if is not running, starts; if has changed, restart 

podman compose down # stop the containers
podman compose down # always exits 0; if running, stop; if is not running, does nothing

**Comment by guesant** [comment]
> in my opinion, for the best DX and convenience comming from docker-compose, i think that --replace should be default, or a new mode that restarts if changed, otherwise exists 0 with running state
> 
> the same for podman compose down if the containers are already stopped
> 
> can we have a env for that?
> 
> PODMAN_COMPOSE_BEHAVIOUR=optimistic
> 
> podman compose up -d # starts the containers podman compose up -d # always exits 0; if running and nothing has changed, does nothing; if is not running, starts; if has changed, restart
> 
> podman compose down # stop the containers podman compose down # always exits 0; if running, stop; if is not running, does nothing

i mean, damn, i just like my compose to be up or down, i don't care if it's already running, stopped or needs to be restarted

**Comment by rafalkrupinski** [comment]
@guesant it's not a critical bug but it's unexpected behaviour and you lose logs on restart

**Comment by madwax** [comment]
I would say losing logs IS a critical bug.  I'm running into this as well.

**Comment by mokibit** [comment]
I was unable to reproduce this issue using the following configuration:
Environment:
```
podman-compose version 1.3.0
podman version 5.4.2
```
`docker-compose.yml`:
```
services:
  myservice:
    image: alpine
    volumes:
      - ./mydir:/mydir:U
    command: touch /mydir/myfile
```
Test steps:
```
podman-compose up
podman-compose up
```
Both commands completed successfully with clean output.

The issue has been resolved by https://github.com/containers/podman-compose/pull/1294

@p12tic  this issue can be closed.

**Comment by maurerle** [comment]
@mokibit I still have this issue using latest debian trixie 13:

```console
$ podman compose up -d
48f3e9d54ca225ac45eea7053d84850a05ee30bc484c9b30446eaa2a9fcea7f3
3d79945f137ae4bdd26cb06134e34615cf8e2e22d815124b624a438cba4e9126
pdm_myservice_1
$ podman compose up -d
Error: creating container storage: the container name "pdm_myservice_1" is already in use by 3d79945f137ae4bdd26cb06134e34615cf8e2e22d815124b624a438cba4e9126. You have to remove that container to be able to reuse that name: that name is already in use, or use --replace to instruct Podman to do so.
pdm_myservice_1
$ cat compose.yml 
services:
  myservice:
    image: alpine
    volumes:
      - ./mydir:/mydir:U
    command: touch /mydir/myfile
$ podman compose version
podman-compose version 1.3.0
podman version 5.4.2
```

But I hope this is solved upstream, as my versions are quite dated now.
