### ISSUE TITLE
volume mounted as type "bind" instead of "volume"

### ISSUE THREAD

**Issue by mschz** [containers/podman-compose#207]
Hi all,
I'm training myself Podman based on a Dock course and faced an issue with podman-compose related to volumes. My docker-compose.yml files looks like this (environment directives have been removed):
```
version: '3'
services:
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
```
The Dockerfile.dev among other activities runs "npm install" and thereby populates a directory "node_modules" with lots of dependencies.

If I execute "podman-compose up" everything is set up and started, but the nodejs server fails to start. I analysed the output of "podman-compose up" and found our what's causing my problem, it's the "--mount" option of "podman start". The two relevant commands executed by "podman-compose" are:
```
podman volume inspect complex_server_2ad5d7cee913d733ad04aafde20a26db || podman volume create complex_server_2ad5d7cee913d733ad04aafde20a26db
Error: no volume with name "complex_server_2ad5d7cee913d733ad04aafde20a26db" found: no such volume
podman create --name=complex_server_1 --pod=complex --label io.podman.compose.config-hash=123 --label io.podman.compose.project=complex --label io.podman.compose.version=0.0.1 --label com.docker.compose.container-number=1 --label com.docker.compose.service=server -e REDIS_HOST=redis -e REDIS_PORT=6379 -e PGUSER=postgres -e PGHOST=postgres -e PGDATABASE=postgres -e PGPASSWORD=postgrep_password -e PGPORT=5432 --mount type=bind,source=/home/mschmitz/.local/share/containers/storage/volumes/complex_server_2ad5d7cee913d733ad04aafde20a26db/_data,destination=/app/node_modules,bind-propagation=Z --mount type=bind,source=/home/mschmitz/work/various-tests/podman/images/complex/./server,destination=/app --add-host postgres:127.0.0.1 --add-host complex_postgres_1:127.0.0.1 --add-host redis:127.0.0.1 --add-host complex_redis_1:127.0.0.1 --add-host server:127.0.0.1 --add-host complex_server_1:127.0.0.1 complex_server
```

Using "--mount type=bind,source=/home/mschmitz/.local/share/containers/storage/volumes/complex_server_2ad5d7cee913d733ad04aafde20a26db/_data,destination=/app/node_modules,bind-propagation=Z" results in entirely hiding the content of the images "node_modules" directory. This is exactly should happen according to the Docker documentation.

However, it's different from what happens when using "docker-compose". Like "podman-compose" a volume is created, but it's not mounted as a "bind mount", but a "volume".

Therefore I executed all "podman" commands which "podman-compose" executes but changed the "podman create" command mentioned above as regards the first "--mount" option. Using "--mount type=volume,source=complex_server_2ad5d7cee913d733ad04aafde20a26db" does the job. Podman populates the volume with the content of the image, nodejs finds all dependencies and starts up.

To me it looks like the command issued by "podman-compose" to mount a volume must be changed.

BR,
Michael.

**Comment by xcffl** [comment]
It has been fixed at https://github.com/containers/podman-compose/blob/294f8ee37bb37ab0535558182cf41d99dfb3cb11/podman_compose.py#L95

**Comment by mschz** [comment]
Sorry, but it's not fixed. The line you quoted affects parsing the docker-compose.yml file only, but the problem is actually with generating the podman commands to be executed when bringing up the container(s). I investigated the code and found that two things are wrong:

1. mount_dict_vol_to_bind() changes the volumes type property to "bind" even if the volume definition didn't include any colon (like e.g. "volume: - /existing/directory/in/image"). For these kind of volumes - and only for these - the variable vol_name_orig will have a value of None. The patch attached makes sure that the type property isn't changed to allow mount_desc_to_args() to handle this case appropriately.
2. mount_desc_to_args() doesn't support mount arguments like "--mount type=volume,source=XXX,destination=YYY" which is needed for initially populating the volume with the contents of the existing directory of the image which must happen in some cases (cf. https://docs.docker.com/storage/). The patch attached handles that in case a mount description "type" property is "volume".

Now the example from my training material work fine.

Please note that I'm neither a Python developer nor did I understand all the details of the code, but I hope the patch doesn'r break anything and at least shows how to properly handle definitions like

```
volume:
  - /existing/directory/in/image
```

in a docker-compose.yml file.
[volume-patch.zip](https://github.com/containers/podman-compose/files/5069155/volume-patch.zip)
