### ISSUE TITLE
Error: error adding pod to state: name "docker" is in use: pod already exists

### ISSUE THREAD

**Issue by cathaysia** [containers/podman-compose#375]
This should be a dup of https://github.com/containers/podman-compose/issues/243, but I still want reopen one to wakeup you.

For convenience, I place some compose files in a dir:

docker
├── aria2.yml
├── sourcegraph.yml
└── whistle.yml

And I run these by podman-compose -f xxx.yml up -d. I create these one by one.

So, I create aria2.yml first, then sourcegraph.yml.

Although sourcegraph.yml can by created, but it listen error ports:
```                                                           
6287c2e02ee0  docker.io/p3terx/aria2-pro:latest                7 days ago     Up 19 hours ago   0.0.0.0:6800->6800/tcp, 0.0.0.0:6888->6888/tcp, 0.0.0.0:6888->6888/udp  docker_aria2-pro_1
09bdb1452d94  docker.io/sourcegraph/server:3.34.2              9 minutes ago  Up 9 minutes ago  0.0.0.0:6800->6800/tcp, 0.0.0.0:6888->6888/tcp, 0.0.0.0:6888->6888/udp  docker_sourcegraph_1
```

So my sourcegraph can not work.

The root cause is sourcegraph has the same pod with aria2 "docker". The "docker" is the dir name.

@shunkica had mention that serveice's name as pod name, it is error obvious. https://github.com/containers/podman-compose/issues/243#issuecomment-802691015

In my opintion, a pod name should has this format: dirname-filename. That is, sourcegraph's pod name should be docker-sourcegraph, then aria2's pod name should be docker-aria2.

Please fix this. :(

**Comment by muayyad-alsadi** [comment]
@cathaysia  please use podman-compose 1.x  and podman version 3.4

```
pip3 install --user 'podman-compose>1.0'
```

because in this version we no longer create a pod and put all contains in it.

if you have to use older version please pass `-p`  to set different project name

**Comment by muayyad-alsadi** [comment]
> In my opintion, a pod name should has this format: dirname-filename. That is, sourcegraph's pod name should be docker-sourcegraph, then aria2's pod name should be docker-aria2.

there should be no compose "filename" with respect to stack, because a stack might be multiple files like `docker-compose.yml` and `docker-compose.override.yml`

the term that describes the stack is project name (defaults to directory name) and you pass it with `-p`

**Comment by muayyad-alsadi** [comment]
yes, it should solve it because in 1.0.2 we don't create pods manually.

please confirm this and close this.

**Comment by daveisfera** [comment]
I'm running 1.0.6 from homebrew and this is still happening. Is that a known issue?
