### ISSUE TITLE
podman-compose doesn't support

### ISSUE THREAD

**Issue by mrishab** [containers/podman-compose#551]
## Is your feature request related to a problem? Please describe.
podman-compose ignores the [platform option](https://docs.docker.com/compose/compose-file/#platform) in the compose YAML file.

I am trying to use this parameter to override the platform value for mysql docker image so it can run on Mac M1.
```
## docker-compose.yml

version: '3.9'

services:
  mysql-db:
    platform: linux/x86_64
    image: mysql:8.0.23
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
```
```
$ podman-compose up -d
```
```
['podman', '--version', '']
using podman version: 4.2.0
** excluding:  set()
['podman', 'network', 'exists', 'my-service_default']
podman run --name=my-service_mysql-db_1 -d --label io.podman.compose.config-hash=123 --label io.podman.compose.project=my-service --label io.podman.compose.version=0.0.1 --label com.docker.compose.project=my-service --label com.docker.compose.project.working_dir=/Users/rishabmanocha/src/github.com/deliverr/my-service --label com.docker.compose.project.config_files=docker-compose-test.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=mysql-db -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=db -e MYSQL_USER=user -e MYSQL_PASSWORD=password --net my-service_default --network-alias mysql-db -p 3306:3306 mysql:8.0.23 mysqld --default-authentication-plugin=mysql_native_password
WARNING: image platform ({amd64 linux  [] }) does not match the expected platform ({arm64 linux  [] })
328bba2de1a48c977076d23784cb7c9e494ff7f1b6038a4312af52d795b80db9
exit code: 0
```
## Describe the solution you'd like
The generated podman run command should include --platform flag with the value provided.

## Describe alternatives you've considered
N/A

## Additional context
Device is Mac M1 Pro.

**Comment by pluskal** [comment]
There is a PR adding this functionality https://github.com/containers/podman-compose/pull/520

**Comment by kderck** [comment]
I'm having the same issue. The aforementioned PR has been closed and not merged.

**Comment by kohpai** [comment]
Hi there!

I'm having this same problem and would like to know what would be a workaround here.
I'm using Mac Mini M2 Pro and Podman. Can I just run docker-compose together and the `platform` options will be applied?

**Comment by jmsgrogan** [comment]
For anyone watching or stumbling on this I believe the feature was since added here: https://github.com/containers/podman-compose/pull/1009 so should be working ok now.

**Comment by junglebells** [comment]
> For anyone watching or stumbling on this I believe the feature was since added here: [#1009](https://github.com/containers/podman-compose/pull/1009) so should be working ok now.

using Podman on FreeBSD - this issue is still not working. sudo podman-compose pull still ignores the "platform" in YAML and defaults based on host os/ arch

`podman-compose version 1.3.0
podman version 5.6.1
`

**Comment by kohpai** [comment]
> For anyone watching or stumbling on this I believe the feature was since added here: [#1009](https://github.com/containers/podman-compose/pull/1009) so should be working ok now.

Just want to confirm that this works for me on Mac M2. I can specify linux/amd64

**Comment by halcyondazer** [comment]
i also use freebsd, the issue has not been fixed in version 1.5.0
i doubt the validity of this project existing if basic functionality like this has been broken the past 4 years without that changing

this blocks a whole series of non-linux systems of working with containers

i seem to have to revert to VMs just to run containers... so why use containers?

**Comment by halcyondazer** [comment]
@junglebells do you also have this issue still?

**Comment by junglebells** [comment]
> [@junglebells](https://github.com/junglebells) do you also have this issue still?

I stopped using podman/freebsd, so I can’t say anymore. However as a workaround I was pulling the image manually to avoid podman compose pulling the incorrect image

**Comment by Markethh** [comment]
Can anyone provide an update on this issue? `podman compose up --build` still seems to not support the `platform` option in compose files.

Building separately with the platform arg (e.g. `podman build --platform "linux/amd64"`) works, but as you can imagine having compose supported would be a massive benefit.

**Comment by kworr** [comment]
Let's say it's not **fully** supported on FreeBSD (?maybe other systems).

So we have:
- FreeBSD/amd64, podman-compose 1.5.0, podman 5.8.2
- compose.yaml:
  - platform: linux/amd64
  - os: linux

```
#podman compose pull
Trying to pull ghcr.io/vectorize-io/hindsight:latest-slim...
Error: unable to copy from source docker://ghcr.io/vectorize-io/hindsight:latest-slim: choosing an image from manifest list docker://ghcr.io/vectorize-io/hindsight:latest-slim: no image found in image index for architecture "amd64", variant "", OS "freebsd"
```

```
# podman compose up -d
time="2026-05-18T09:33:58+03:00" level=warning msg="StopSignal SIGTERM failed to stop container hindsight_hindsight_1 in 10 seconds, resorting to SIGKILL"
hindsight_hindsight_1
hindsight_hindsight_1
f9a15f8d7c720e1accb84ddc7880ecd52412a85d2abff152b8df2ea85545b5d0
c60b1d09ebfc0863164a584989dbb9c3a8b632a6a7f3880490eb37e8d67f920a
Trying to pull ghcr.io/vectorize-io/hindsight:latest-slim...
Getting image source signatures
Copying blob sha256:2ae25566cd0883fcec630a25e9a6a2fccf546ceed4b3c836cfdfbcc2ae41408e
Copying blob sha256:fb4c70443787d9baef637d0b257f21b935d5feb6481f1ccdf4d07f48b2e393c1
Copying blob sha256:57fb71246055257a374deb7564ceca10f43c2352572b501efc08add5d24ebb61
Copying blob sha256:01f59aef9b5c2caa2870aa8b9b8b5806ea3c36d893cd6e2467e252fc1b1fea46
Copying blob sha256:6f92665ed17afc6850bfbeb3fb681d6e1038fe59e2020ab126b859ec572da21b
Copying blob sha256:a31ee4ed898439df8952cfc7a564924141a7d6c704ceb5ffe1bb6f92e143fddc
Copying blob sha256:8a16b54334a008de79bf6df198c6ebd3edff0772b6ee5fd891aa2cfb15ef9898
Copying blob sha256:26e6c1148b3d5450a365c9a2861437a6cbb5d67770f3a66c0a76c7811055f860
Copying blob sha256:a3ac17ba140f5cb46a9eb6cabe4fc88f6cfebde7675355cb924230991c1d587a
Copying blob sha256:9324785c51ca7ef5de28f29334a2fe0c4f0d3e98e674503fc8d303f52f0b635b
Copying blob sha256:97db929946f725c8d43c7de9f8533edb12e001691a08c86e20222d759a265d62
Copying blob sha256:8aabee33b3fe2629550eeeb3101db851e277fc7c77eaa60f51784c11d81a5f1f
Copying blob sha256:aad747d54e978d3ba02ea2b738ce4b030ac4f4564351c35dc4c58b7430c50adb
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying blob sha256:074770dead24477c013ef0079f9553d4b6cdc91ed2da31f4404fe9eb2676bd64
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying blob sha256:b865c4f1ba684589755040f66e34a8160bc49fe08af2c75cc1892568f49d1d23
Copying blob sha256:2e30e4b7c675447355429f638d075ff078d15b80a3b32e5f3cc7133b23199885
Copying blob sha256:e520378d7c43dbe07c60d3f40c835ceb92bef1dc61bd3206850ba3e9b67403a6
Copying blob sha256:77c9a06de0549abe6800f7cf84574f5fb27361cca98440424ee95c00692f33c1
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
Copying config sha256:af02aee1a7f867f68def6b7ca11dc2a4e52eb4806f6be44d8cdf81ced4fcd55e
Writing manifest to image destination
ccacf3ef637af6715c856572f83c976b991d972dd0c4a219155f2de370d6c764
hindsight_hindsight_1
```

So for me it looks like even `os: linux` is enough to make `up` work, but `pull` is still looking for wrong images.

**Comment by gunnarwustl** [comment]
> Can anyone provide an update on this issue? `podman compose up --build` still seems to not support the `platform` option in compose files.
> 
> Building separately with the platform arg (e.g. `podman build --platform "linux/amd64"`) works, but as you can imagine having compose supported would be a massive benefit.

This is my experience as well on an M3 Macbook. Within our team we've simply resigned to use Docker in any situation where compose is needed.
